// Domain events emitted on the event bus after a DB commit.
// Listeners (audit, notifications) subscribe to these.
module.exports = Object.freeze({
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGGED_IN: 'USER_LOGGED_IN',
  USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
  USER_LOGGED_OUT: 'USER_LOGGED_OUT',
  STAFF_CREATED: 'STAFF_CREATED',

  WORKSHOP_CREATED: 'WORKSHOP_CREATED',
  WORKSHOP_UPDATED: 'WORKSHOP_UPDATED',
  WORKSHOP_PUBLISHED: 'WORKSHOP_PUBLISHED',
  WORKSHOP_CANCELLED: 'WORKSHOP_CANCELLED',
  WORKSHOP_COMPLETED: 'WORKSHOP_COMPLETED',
  SPOT_REGISTRARS_ASSIGNED: 'SPOT_REGISTRARS_ASSIGNED',

  REGISTRATION_CONFIRMED: 'REGISTRATION_CONFIRMED',
  WAITLIST_JOINED: 'WAITLIST_JOINED',
  WAITLIST_PROMOTED: 'WAITLIST_PROMOTED',
  REGISTRATION_CANCELLED: 'REGISTRATION_CANCELLED',
  REGISTRATION_STATUS_CHANGED: 'REGISTRATION_STATUS_CHANGED',

  MARKED_PRESENT: 'MARKED_PRESENT',
  CHECKED_IN: 'CHECKED_IN',
  MARKED_NO_SHOW: 'MARKED_NO_SHOW',

  WORKSHOP_REMINDER: 'WORKSHOP_REMINDER',
  CERTIFICATE_AVAILABLE: 'CERTIFICATE_AVAILABLE',
});
